import { describe, expect, it } from "vitest";
import { computeDashboardMetrics, type Financial } from "../src/lib/metrics";

const makeFinancial = (overrides: Partial<Financial> = {}): Financial => ({
  deliveryAmount: 0,
  deliveryRub: 0,
  stornoDeliveryAmount: 0,
  storageAmount: 0,
  penalty: 0,
  additionalPayment: 0,
  deductionAmount: 0,
  ppvzForPay: 0,
  ppvzSalesTotal: undefined,
  acceptance: 0,
  retailAmount: 0,
  retailPrice: undefined,
  returnAmount: 0,
  docTypeName: "Продажа",
  nmId: 101,
  supplierArticle: "SKU-101",
  supplierOperName: undefined,
  bonusTypeName: undefined,
  ...overrides,
});

describe("dashboard numeric regressions", () => {
  it("computes fixed dashboard totals from deterministic seed data", () => {
    const result = computeDashboardMetrics({
      sales: [],
      orders: [
        {
          nmId: 101,
          totalPrice: 1200,
          priceWithDisc: 1000,
          quantity: 2,
          isCancel: false,
          date: "2026-04-01",
        },
        {
          nmId: 102,
          totalPrice: 900,
          priceWithDisc: 800,
          quantity: 1,
          isCancel: true,
          date: "2026-04-02",
        },
      ],
      financials: [
        makeFinancial({
          nmId: 101,
          retailPrice: 1000,
          retailAmount: 900,
          ppvzForPay: 700,
          deliveryRub: 40,
        }),
        makeFinancial({
          nmId: 101,
          retailPrice: 1200,
          retailAmount: 1080,
          ppvzForPay: 840,
          deliveryRub: 45,
        }),
        makeFinancial({
          nmId: 102,
          retailPrice: 800,
          retailAmount: 720,
          ppvzForPay: 520,
          deliveryRub: 30,
        }),
        makeFinancial({
          nmId: 101,
          retailPrice: -1000,
          retailAmount: -900,
          ppvzForPay: -700,
          deliveryRub: 25,
          docTypeName: "Возврат",
        }),
        makeFinancial({
          nmId: 0,
          docTypeName: "",
          storageAmount: 50,
          acceptance: 20,
          penalty: 10,
          additionalPayment: 15,
        }),
        makeFinancial({
          nmId: 0,
          docTypeName: "",
          deductionAmount: 100,
          bonusTypeName: "Оказание услуг «WB Продвижение», документ 1",
        }),
        makeFinancial({
          nmId: 0,
          docTypeName: "",
          deductionAmount: 40,
          bonusTypeName: "Manual service fee",
        }),
      ],
      costs: [
        { nmId: 101, cost: 300 },
        { nmId: 102, cost: 200 },
      ],
      campaigns: [{ spent: 9999 }],
      nmReports: [
        {
          openCardCount: 100,
          addToCartCount: 25,
          ordersCount: 5,
          buyoutsCount: 4,
        },
      ],
    });

    expect({
      openCardCount: result.openCardCount,
      addToCartCount: result.addToCartCount,
      crToCart: result.crToCart,
      crToOrder: result.crToOrder,
      ordersRevenue: result.ordersRevenue,
      ordersCount: result.ordersCount,
      avgOrderValue: result.avgOrderValue,
      cancelledRevenue: result.cancelledRevenue,
      cancelledCount: result.cancelledCount,
      cancelRate: result.cancelRate,
      salesSeller: result.salesSeller,
      returnsSeller: result.returnsSeller,
      revenueSeller: result.revenueSeller,
      salesWbDisc: result.salesWbDisc,
      returnsWbDisc: result.returnsWbDisc,
      revenueWbDisc: result.revenueWbDisc,
      wbDiscountPct: result.wbDiscountPct,
      forPaySales: result.forPaySales,
      forPayReturns: result.forPayReturns,
      forPayTotal: result.forPayTotal,
      salesCount: result.salesCount,
      returnsCount: result.returnsCount,
      buyoutsCount: result.buyoutsCount,
      returnRate: result.returnRate,
      buyoutRate: result.buyoutRate,
      avgCheck: result.avgCheck,
      cogs: result.cogs,
      avgCost: result.avgCost,
      grossProfit: result.grossProfit,
      commission: result.commission,
      logistics: result.logistics,
      storage: result.storage,
      acceptance: result.acceptance,
      ads: result.ads,
      penalties: result.penalties,
      deductions: result.deductions,
      compensation: result.compensation,
      mpExpenses: result.mpExpenses,
      profitBeforeTax: result.profitBeforeTax,
      tax: result.tax,
      profit: result.profit,
      roi: result.roi,
      payoutToAccount: result.payoutToAccount,
      salesNoCost: result.salesNoCost,
      returnsNoCost: result.returnsNoCost,
    }).toMatchInlineSnapshot(`
      {
        "acceptance": 20,
        "addToCartCount": 25,
        "ads": 100,
        "avgCheck": 1000,
        "avgCost": 250,
        "avgOrderValue": 500,
        "buyoutRate": 100,
        "buyoutsCount": 2,
        "cancelRate": 50,
        "cancelledCount": 1,
        "cancelledRevenue": 800,
        "cogs": 500,
        "commission": 640,
        "compensation": 15,
        "crToCart": 25,
        "crToOrder": 20,
        "deductions": 40,
        "forPayReturns": 700,
        "forPaySales": 2060,
        "forPayTotal": 1360,
        "grossProfit": 1500,
        "logistics": 140,
        "mpExpenses": 985,
        "openCardCount": 100,
        "ordersCount": 2,
        "ordersRevenue": 1000,
        "payoutToAccount": 1360,
        "penalties": 10,
        "profit": 407,
        "profitBeforeTax": 515,
        "returnRate": 50,
        "returnsCount": 1,
        "returnsNoCost": 0,
        "returnsSeller": 1000,
        "returnsWbDisc": 900,
        "revenueSeller": 2000,
        "revenueWbDisc": 1800,
        "roi": 81.39999999999999,
        "salesCount": 3,
        "salesNoCost": 0,
        "salesSeller": 3000,
        "salesWbDisc": 2700,
        "storage": 50,
        "tax": 108,
        "wbDiscountPct": 10,
      }
    `);

    expect(result.cogsPercent).toBe(25);
    expect(result.grossProfitPercent).toBe(75);
    expect(result.commissionPercent).toBe(32);
    expect(result.mpExpensesPercent).toBe(49.25);
    expect(result.profitBeforeTaxPercent).toBe(25.75);
    expect(result.profitPercent).toBeCloseTo(20.35, 2);
    expect(result.taxPercent).toBeCloseTo(5.4, 2);
  });
});
